### ISSUE TITLE
When I tried to cross compile tcpdump for riscv64, the tcpdump configure script didn't find libpcap

### ISSUE THREAD

**Issue by ultrariscwangjiahao** [the-tcpdump-group/tcpdump#1082]
When I do ./configure CC=riscv-linux-gcc,it is failed.
If I set nothing parameter with CC, it will generate Makefile.But I cross compile libpcap successfully.And I copy libpcap/bin lib share to tcpdump/.
[tcpdump_config.log](https://github.com/the-tcpdump-group/tcpdump/files/12595766/tcpdump_config.log)
[libpcap_config.log](https://github.com/the-tcpdump-group/tcpdump/files/12595767/libpcap_config.log)

**Comment by guyharris** [comment]
> But I cross compile libpcap successfully.

Did you put the tcpdump and libpcap source files in subdirectories of the same directory, so that, for example, you have, in that directory, libpcap-1.11.0-PRE-GIT and tcpdump-5.0.0-PRE-GIT source directories?

If not, after you cross-compiled libpcap, did you install it?

The errors from the configure script for tcpdump are:

```
configure:6027: riscv64-unknown-linux-gnu-gcc -o conftest -g -O2   conftest.c -lpcap  >&5
/mnt/disk/ssw/toolchain/install/urgcc-3.11.74/linux/bin/../lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: cannot find -lpcap: No such file or directory
```

which means that the cross-compiler, when run by the configure script, didn't find libpcap in any of the directories in which it normally looks for libraries.

**Comment by ultrariscwangjiahao** [comment]
So,I should put the tcpdump and libpcap source file in the same directory.Such as:/home/user/code/tcpdump/(tcp source code) and /home/user/code/libpcap/(libpcap source code)? or /home/user/code/(tcpdump souce code and libcap source code) ?

**Comment by guyharris** [comment]
> So,I should put the tcpdump and libpcap source file in the same directory.Such as:/home/user/code/tcpdump/(tcp source code) and /home/user/code/libpcap/(libpcap source code)? or /home/user/code/(tcpdump souce code and libcap source code) ?

Do it as /home/user/code/(tcpdump source code and libpcap source code), for example,  /home/user/code/tcpdump-5.0.0-PRE-GIT, with the tcpdump source code in the /home/user/code/tcpdump-5.0.0-PRE-GIT directory, and /home/user/code/libpcap-1.11.0-PRE-GIT, with the libpcap source code in the /home/user/code/libpcap-1.11.0-PRE-GIT directory.

If you are using autotools (the configure scripts) rather than CMake, there are two ways to build libpcap from source and then build tcpdump from source using that libpcap:

1. put the two source file directories in the same parent directory, change to the libpcap source directory, run the configure script, run make, change to the tcpdump source directory, run the configure script, and run make;
2. put them wherever you want, change to the libpcap source directory, run the configure script, run make, do a "make install", change to the tcpdump source directory, run the configure script, and run make.

**Comment by ultrariscwangjiahao** [comment]
Thanks very much!!Now I can cross compile tcpdump for riscv64 successfully.
