### ISSUE TITLE
tcpdump -r pcap file error

### ISSUE THREAD

**Issue by kogii179** [the-tcpdump-group/tcpdump#1098]
My tcpdump version is 4.99.1libpcap version 1.9.1 (with TPACKET_V3)
When I used tcpdump to read a pcap file, some segment maybe "rmnet_data0 Out IP0 (invalid)"
What is this mean, how can I fix it?

**Comment by guyharris** [comment]
> "rmnet_data0 Out IP0 (invalid)"
> What is this mean

It means that the packet, as delivered to tcpdump by libpcap:

1. had a "cooked capture" header, so that the interface on which the packet arrived can be guessed at, and thus was probably captured on a machine with a Linux kernel;
2. probably arrived on the interface named "rmnet_data0" *IF* the pcap file was captured on the same machine as the one on which you're running tcpdump (otherwise, it may be a completely bogus interface name);
3. was transmitted by the machine on which the capture was being made ("Out");
4. had what appears to be a bogus IP header, with the IP protocol version field being 0 rather than 4 (IPv4) or 6 (IPv6).

> how can I fix it?

That depends on the reason why it occurred.

We need some  more information to determine that.

On what type of machine was the pcap file captured and written, what operating system was it running, and what program was used to capture the packets?

On what type of machine are you running tcpdump to read the file, and what operating system was it running?

**Comment by infrastation** [comment]
If the file was generated using libpcap 1.10.1, this potentially could have the same root cause as #1092.

**Comment by infrastation** [comment]
It was 1.9.1, as the original comment says. @kogii179, please provide the additional information as requested, or this bug report will be closed.

**Comment by infrastation** [comment]
As advised.
