### ISSUE TITLE
Is there any way to print bytes from specific offset?

### ISSUE THREAD

**Issue by brookhong** [the-tcpdump-group/tcpdump#427]
For example,
sudo tcpdump -XX -S tcp[4:8] -i 1 tcp port 8090

to print the bytes between the 4th and the 8th of tcp payload.

Can we support this feature, It helps a lot for analysing protocals?

**Comment by guyharris** [comment]
`-S` tells tcpdump to "Print absolute, rather than relative, TCP sequence numbers.", so it won't be `-S tcp[4:8]`.

Fortunately, tcpdump now uses `getopt_long()`, so it could use something such as `--print-bytes`.

**Comment by stevekay** [comment]
I have something similar which may suit brookhong's requirement. 
https://github.com/stevekay/tcpdump

    $ sudo ./tcpdump -r /tmp/skcap -XX -c 1 tcp
    reading from file /tmp/skcap, link-type EN10MB (Ethernet)
    09:44:50.559756 IP localhost.localdomain.ssh > 192.168.124.1.55124: Flags [P.], seq    191837562:191837694, ack 304548772, win 262, length 132

        0x0000:  0050 56c0 0008 000c 2941 e0ab 0800 4510  .PV.....)A....E.
        0x0010:  00ac 3e8f 4000 4006 81d6 c0a8 7c84 c0a8  ..>.@.@.....|...
        0x0020:  7c01 0016 d754 0b6f 357a 1227 0ba4 5018  |....T.o5z.'..P.
        0x0030:  0106 7a75 0000 f7f3 cabf 637e eac0 7c75  ..zu......c~..|u
        0x0040:  12c2 76f4 fd35 33bf e1ee 2846 394e 588c  ..v..53...(F9NX.
        0x0050:  9b6c 6b2e d23b 5afd 97b5 313a c4ef 771b  .lk..;Z...1:..w.
        0x0060:  11de d530 445e 1161 3853 1dc6 503e 353c  ...0D^.a8S..P>5<
        0x0070:  c369 6393 7339 2105 b118 7628 c3b3 95b9  .ic.s9!...v(....
        0x0080:  2df2 3901 34d9 a992 388b caf7 250b 1f4b  -.9.4...8...%..K
        0x0090:  18e5 8340 718d c547 a69c 05fd 2987 d095  ...@q..G....)...
        0x00a0:  7042 5caa f1d9 a444 4693 6383 63f0 ba4e  pB\....DF.c.c..N
        0x00b0:  b6f1 7f28 f7c6 e068 2139                 ...(...h!9
    $ sudo ./tcpdump -r /tmp/skcap --print-bytes 0:4 -XX -c 1 tcp
    reading from file /tmp/skcap, link-type EN10MB (Ethernet)
    09:44:50.559756 IP localhost.localdomain.ssh > 192.168.124.1.55124: Flags [P.], seq 191837562:191837694, ack 304548772, win 262, length 132

        0x0000:  4510 00ac                                E...
    $

**Comment by guyharris** [comment]
Comments on that change:

1. Please don't use "-P" - OS X's tcpdump uses it to mean "write pcap-ng files", and when libpcap gets support for writing pcap-ng files added to it, we'll be using it for the same purpose, so as to avoid gratuitous command-line option differences.  "--print-bytes" suffices, and doesn't have to be mapped to a short option.

2. The usage message says "--print-bytes proto[start:end]", but the actual *code* does "--print-bytes start:end". 

3. "Print bytes between the 4th and 8th byte of the TCP payload" could only be implemented by "--print-bytes start:end" for packets where the IP and TCP headers have the same length in all packets, i.e. have the same possibly-empty set of options, and for which the same version (IPv4 or IPv6) of IP is being used, so that the offset from the beginning of the IP header to the TCP payload is the same for all packets.  "--print-bytes proto[start:end]" would support that with no issues, but would require changes to be made throughout tcpdump.

**Comment by brookhong** [comment]
The printed bytes are within IP header, not in specified proto payload.

`tcpdump -X -s 18` can do the almost same job.

**Comment by stevekay** [comment]
Thanks both for the feedback.

* Wasn't using "-P" as an argument, merely as a longopt type, so all good there.

* Usage message fixed.

* The print bytes/payload aspect was confusing.  So I've made it select from bytes within the packet once link layer details are stripped.  So a good example below.

        $ ./tcpdump -r tests/mptcp.pcap -c 1 -XX
        reading from file tests/mptcp.pcap, link-type EN10MB (Ethernet)
        05:56:35.701161 IP 10.2.1.2.35961 > 10.1.1.2.ssh: Flags [S], seq 2912457561, win 14600, options [mss 1460,sackOK,TS val 4294943152 ecr 0,nop,wscale 6,mptcp capable csum {0x9c9eabd1e46a33b2}], length 0
                0x0000:  1651 5304 3f55 f28c f524 1b21 0800 4500  .QS.?U...$.!..E.
                0x0010:  0048 32e9 4000 4006 f1c0 0a02 0102 0a01  .H2.@.@.........
                0x0020:  0102 8c79 0016 ad98 9359 0000 0000 d002  ...y.....Y......
                0x0030:  3908 da99 0000 0204 05b4 0402 080a ffff  9...............
                0x0040:  a1b0 0000 0000 0103 0306 1e0c 0081 9c9e  ................
                0x0050:  abd1 e46a 33b2                           ...j3.
        $ ./tcpdump -r tests/mptcp.pcap -c 1 -X
        reading from file tests/mptcp.pcap, link-type EN10MB (Ethernet)
        05:56:35.701161 IP 10.2.1.2.35961 > 10.1.1.2.ssh: Flags [S], seq 2912457561, win 14600, options [mss 1460,sackOK,TS val 4294943152 ecr 0,nop,wscale 6,mptcp capable csum {0x9c9eabd1e46a33b2}], length 0
                0x0000:  4500 0048 32e9 4000 4006 f1c0 0a02 0102  E..H2.@.@.......
                0x0010:  0a01 0102 8c79 0016 ad98 9359 0000 0000  .....y.....Y....
                0x0020:  d002 3908 da99 0000 0204 05b4 0402 080a  ..9.............
                0x0030:  ffff a1b0 0000 0000 0103 0306 1e0c 0081  ................
                0x0040:  9c9e abd1 e46a 33b2                      .....j3.
        $ ./tcpdump -r tests/mptcp.pcap -c 1 -X --print-bytes 16:31
        reading from file tests/mptcp.pcap, link-type EN10MB (Ethernet)
        05:56:35.701161 IP 10.2.1.2.35961 > 10.1.1.2.ssh: Flags [S], seq 2912457561, win 14600, options [mss 1460,sackOK,TS val 4294943152 ecr 0,nop,wscale 6,mptcp capable csum {0x9c9eabd1e46a33b2}], length 0
                0x0010:  0a01 0102 8c79 0016 ad98 9359 0000 00    .....y.....Y...
        $ 

* Updated code is at https://github.com/stevekay/tcpdump

**Comment by guyharris** [comment]
> Wasn't using "-P" as an argument, merely as a longopt type, so all good there.

If you use something as a longopt type, you make it unusable as an argument for any purpose other than as a short name for the long option in question.  That's why we have the `OPTION_` definitions - to avoid that sort of collision - and that collision *will* happen once we add pcap-ng writing support to libpcap and then to tcpdump.

Define `OPTION_PRINT_BYTES` as 131, and use it instead of `'P'`.

**Comment by stevekay** [comment]
Guy - thanks for the advice, wasn't aware of that.
Repo updated.
https://github.com/stevekay/tcpdump/commit/5540dff9289c07f871084e3d7f698d1c17eb62a8

**Comment by infrastation** [comment]
If anybody still has a genuine need for this feature, please prepare the changes and open a pull request. Closing.
