### ISSUE TITLE
filter pcap with multiple filter strings to multiple files

### ISSUE THREAD

**Issue by ogreenz** [the-tcpdump-group/tcpdump#481]
Hi,

If possible I would like the option to filter the same pcap file with multiple filter strings, each filter will create a seperate file. A workaround I use instead is filtering the same file multiple times. This causes unwanted latency in the filtering process because of the reiteration of the pcap's packets.

**Comment by guyharris** [comment]
I.e., you want to be able to do something such as

    tcpdump -r {input file} -f {filter1} -w {file1} -f {filter2} -w {file2} ...

where all packets in {input file} that match {filter1} are written to {file1}, all packets in {input file} that match {filter2} are written to {file2}, etc.?

**Comment by ogreenz** [comment]
Yes exactly.

**Comment by abhatikar** [comment]
I need tcpdump filter wlan probe requests and  radiotap.dbm_antsignal >= -60.
I could do it in wireshark but could not do it using tcp dump.
Could some one help ?

**Comment by guyharris** [comment]
> I need tcpdump filter wlan probe requests and radiotap.dbm_antsignal >= -60.

That's a separate question, and the answer is "libpcap doesn't support filtering on the radiotap header, so you can't do it with tcpdump".

**Comment by abhatikar** [comment]
Thanks for the answer. But then how does wireshark does it?
I tried to use radiotap.dbm_antsignal >= -60 with wireshark and it works..

**Comment by guyharris** [comment]
Wireshark uses libpcap/WinPcap's filtering mechanism for capture filters; it has its own filtering mechanism, based on its detailed dissection of packets, for display filters.  `radiotap.dbm_antsignal >= -60` is a display filter.

**Comment by abhatikar** [comment]
Thanks for your email.
So to clarify, you are saying that whether it's tcp dump or wireshark both
use libpcap. Libpcap on its own doesn't support radio tap filtering.
However, wireshark does it using a display filter to show 802.11 packets
with radiotap.dbm_antsignal >=-60
In the background it must have captured all 802.11 packets,but display
filter does a post-processing.

**Comment by guyharris** [comment]
> So to clarify, you are saying that whether it's tcp dump or wireshark both
use libpcap.

Yes.  tcpdump uses libpcap to capture live traffic and read capture files, and uses libpcap's filters for both purposes.  Wireshark uses it to capture live traffic, and uses libpcap's filters when capturing.

> However, wireshark does it using a display filter to show 802.11 packets
with radiotap.dbm_antsignal >=-60

Yes.

> In the background it must have captured all 802.11 packets,

All packets that passed whatever filter it used; you *can* filter to capture only probe requests.

> but display filter does a post-processing.

Yes.

**Comment by abhatikar** [comment]
Thanks for answers, I am obliged.

thanks
Abhijeet

So to clarify, you are saying that whether it's tcp dump or wireshark both
use libpcap.

Yes. tcpdump uses libpcap to capture live traffic and read capture files,
and uses libpcap's filters for both purposes. Wireshark uses it to capture
live traffic, and uses libpcap's filters when capturing.

However, wireshark does it using a display filter to show 802.11 packets
with radiotap.dbm_antsignal >=-60

Yes.

In the background it must have captured all 802.11 packets,

All packets that passed whatever filter it used; you *can* filter to
capture only probe requests.

but display filter does a post-processing.

Yes.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/the-tcpdump-group/tcpdump/issues/481#issuecomment-225334427>,
or mute the thread
<https://github.com/notifications/unsubscribe/AHn8j14X8XGm__K3eY9dW4ku3O0f-TfVks5qKiyUgaJpZM4GA2GT>
.

**Comment by bijalthanawala** [comment]
I wish to study this feature request (and implement it if my current skill-level is adequate).

@guyharris: 
I am going with the assumption that you mean capital F (-F) in your comments above (copied here),
because lower case f (-f) switch has seemingly nothing to do with filters.
``tcpdump -r {input file} -f {filter1} -w {file1} -f {filter2} -w {file2} ... ``

Please do correct me if my assumption is not accurate.

**Comment by infrastation** [comment]
This issue has been around for a while, hopefully late is better than never. As far as the original request explains it, there was one input .pcap file and a number of filtering rounds, each of which produced its own output .pcap file, and the problem was that doing that one round at a time didn't work fast enough. The suggested solution was to extend tcpdump to write multiple files, each using its own filter.

If such a solution filtered and wrote the output files in sequence, its performance would be the same as the existing arrangement. To perform better, it would need to filter and to write several files in parallel, which would require making tcpdump multi-threaded.

However, this complication is unnecessary. This particular data flow can be trivially parallelized by running multiple rounds in parallel. If the filtering is CPU-bound, the additional tcpdump processes would immediately scale up by loading more CPU cores. If the input file is large enough to make the filtering disk-bound, that would be simpler to solve using better hardware, for a price.

This way, I consider the original request addressed. Unless anyone objects, it will be closed in 7 days.

**Comment by infrastation** [comment]
It is time.
