### ISSUE TITLE
tcpdump -w does not store packets in file (file size 0)

### ISSUE THREAD

**Issue by easijav** [the-tcpdump-group/tcpdump#485]
Hello,

I am trying to take tcpdump -w on linux. file size always remain 0 and could not store anything although file is being made. eth0 is carrying traffic. I am root user and disk space is more than enough. Can anyone help me out.

    ~ # tcpdump -i eth0 -w testing.cap
    tcpdump: listening on eth0, link-type EN10MB (Ethernet), capture size 96 bytes
    ^Z
    [1]+  Stopped                 tcpdump -i eth0 -w testing.cap
   
    # ls -ltr testing.cap
    -rw-r--r-- 1 root root 0 Oct 14 12:24 testing.cap

**Comment by guyharris** [comment]
libpcap (which tcpdump uses to write out the capture file) uses the C "standard I/O routines", such as `fopen()`, `fwrite()`, etc. to write out file data.  This means that output is stored in a memory buffer and only written to the file when

1. the buffer, which is typically 4K bytes or so, fills up;
2. the file is closed;
3. the program explicitly flushes the buffer.

This means that the file is ***NOT*** guaranteed to contain every single packet seen by tcpdump until tcpdump exits, either because it's given a count of packets to capture or because it's interrupted.

**Comment by easijav** [comment]
Hi,
Thanks for the info. How it can be checked as I can see the described
conditions are fulfilled. Can I trace what actually is happening when
libpcap is called upon?
R//Asim

**Comment by guyharris** [comment]
This is on Linux, so you could use strace to watch what tcpdump does.  You could also run tcpdump with `-U`.  Other than that, no, you can't.

**Comment by gvanem** [comment]
One can also print the binary data to stdout and make it line-buffered (option `-l`):
```
tcdump -i eth0 -lw - > testing.pcap
```

This work even on Windows where stdout is *not* binary, but tcpdump sets into binary-mode.

**Comment by easijav** [comment]
Hellp Guy Harris,

I have taken the strace for this command. Could not find some specific
info. Maybe i overlooked it. Trace is attached.

R//Asim


On Wed, Oct 14, 2015 at 1:11 PM, Guy Harris <notifications@github.com>
wrote:

> This is on Linux, so you could use strace to watch what tcpdump does. You
> could also run tcpdump with -U. Other than that, no, you can't.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/the-tcpdump-group/tcpdump/issues/485#issuecomment-147969172>
> .
>



-- 
asimjaved
Electricle Engg dept
University of Engg & Technology

**Comment by infrastation** [comment]
Can you please make sure tcpdump can receive any packets at all on that interface by running it without `-w` first? If there is some packet exchange, can you run tcpdump again with `-w` and leave it running (don't press Control-Z) for a few minutes and then check the file size in a different terminal? If it is still 0, can you tell the exact Linux distribution and its version and also the version of tcpdump and libpcap (`tcpdump --version` or `tcpdump -h`)? Thank you.

**Comment by easijav** [comment]
Hi Denis,

It clicked to me from your email and i tested it that Control-Z does not
dump the data in file where if i use Control C i have successful .pcap file
data. Do you have any idea if Control Z works or not on tcpdump?

R//Asim

On Wed, Oct 14, 2015 at 6:27 PM, Denis Ovsienko <notifications@github.com>
wrote:

> Can you please make sure tcpdump can receive any packets at all on that
> interface by running it without -w first? If there is some packet
> exchange, can you run tcpdump again with -w and leave it running (don't
> press Control-Z) for a few minutes and then check the file size in a
> different terminal? If it is still 0, can you tell the exact Linux
> distribution and its version and also the version of tcpdump and libpcap (tcpdump
> --version or tcpdump -h)? Thank you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/the-tcpdump-group/tcpdump/issues/485#issuecomment-148048770>
> .
>



-- 
asimjaved
Electricle Engg dept
University of Engg & Technology

**Comment by guyharris** [comment]
On Oct 14, 2015, at 8:23 AM, easijav <notifications@github.com> wrote:


> It clicked to me from your email and i tested it that Control-Z does not
> dump the data in file

There is absolutely no reason to expect it to do so.  ^Z just suspends the current process; tcpdump does *not* catch SIGTSTP and flush the buffer for the capture file before suspending itself, it just gets directly suspended by the kernel.

> where if i use Control C i have successful .pcap file
> data.

That's because tcpdump *does* catch SIGINT, and closes the dump file (flushing the buffers) and exits.

> Do you have any idea if Control Z works or not on tcpdump?

Yes, it works, but "works" is not defined to include flushing buffers, it's defined to mean "the process gets suspended", so, since that happens, it works.

**Comment by guyharris** [comment]
On Oct 14, 2015, at 4:13 AM, easijav <notifications@github.com> wrote:

> I have taken the strace for this command. Could not find some specific
> info. Maybe i overlooked it. Trace is attached.

No, there was nothing attached to your message.

**Comment by easijav** [comment]
Great info. Much appreciated support. Thanks a lot :)

**Comment by nitin122333** [comment]
Hi,
I created one logger app in my android device. So everything is going fine, tcpdump command is executing and it will creating file with name "wlan0.cap" in whatever the path i wanted.
But the problem is every time it will creating empty file. And when i run the tcpdump command in adb shell then it will writing the data packets in that files.
I already tried with different tcpdump commands but still it is not working. Can u help me where is the exact root cause????
