### ISSUE TITLE
64-bit warnings in in_chksum.c & print-sctp.c

### ISSUE THREAD

**Issue by gvanem** [the-tcpdump-group/tcpdump#493]
At line 95 in `in_chksum.c`, gcc 5.1 raises a warning in a 64-bit build:
```
		if ((1 & (unsigned long) w) && (mlen > 0)) {
 			REDUCE;
```
I think it would be better to say:
```
		if ((1 & (uintptr_t) w) && (mlen > 0)) {
 			REDUCE;
```
Isn't `sizeof(uintptr_t)` always the size of the address-bus?  (And *ass-u-ming* all compilers we care about have this type).

The same warning in `print-sctp.c` for line 511:
```
   if( (u_long) endPacketPtr > (u_long) ndo->ndo_snapend)
```

**Comment by guyharris** [comment]
> At line 95 in `in_chksum.c`, gcc 5.1 raises a warning in a 64-bit build:

On UN\*X, or on Windows?  UN\*Xes are usually either ILP32 or LP64, and `unsigned long` is the same bit-width as a pointer on those platforms; 64-bit Windows is LLP64, and `unsigned long` is only 32 bits but pointers are 64-bit.

> Isn't `sizeof(uintptr_t)` always the size of the address-bus?

Not on machines where a reference takes multiple bus cycles because the address bus is narrower than the size of physical addresses and multiple bus cycles are used to provide the address. :-)

However, to quote the C99 standard:

The following type designates an unsigned integer type with the property that any valid pointer to ***`void`*** can be converted to this type, then converted back to pointer to ***`void`***, and the result will compare equal to the original pointer:

***`uintptr_t`***

> And *ass-u-ming* all compilers we care about have this type).

To quote configure.in:

    #
    # Make sure we have a definition for C99's uintptr_t (regardless of
    # whether the environment is a C99 environment or not).
    # 
    AC_TYPE_UINTPTR_T
 
so if you're configuring with autotools, it will guarantee that `uintptr_t` will be defined.

So the only issues would be on DOS and Windows, and we can probably arrange to define `uintptr_t` if, for example, MSVC or MinGW doesn't define it.  However, Microsoft [claims that they support `uintptr_t` at least back to Visual Studio .NET 2003](https://msdn.microsoft.com/en-us/library/323b6b3k(v=vs.71).aspx), so we probably don't need to worry about it.

So I just went with `uintptr_t` in `in_cksum.c` in fd2a4d9ad21d2899af182e383a2d2c70ba8832f6.

I'll look at `print-sftp.c` to see whether it should just be using one of the `ND_TTEST` macros.

**Comment by guyharris** [comment]
And we're already using `uintptr_t` in the `ND_TTEST2` macro anyway.

**Comment by gvanem** [comment]
> On UN*X, or on Windows?

That was on 64-Windows. Using [TDM-MinGW](http://tdm-gcc.tdragon.net/) with gcc 5.1. Thanks for reminding me of `LLP64`.

**Comment by guyharris** [comment]
I changed the `print-sctp.c` code to scan through the packet differently, and to do fewer checks up front and more checks in the process of parsing; it now catches some more errors.  That also eliminated the pointer checks (the `ND_` checks are sufficient, now that it even does an `ND_` check on any padding at the end of a chunk).

**Comment by fxlb** [comment]
@guyharris There is little pcap files in Wireshark git repo. How is done regression tests for Wireshark ?

**Comment by gvanem** [comment]
@guyharris So the only issues would be on DOS and Windows,

This reminds me of my DOS-port of libpcap (I've also built tcpdump on DOS/djgpp. But that is another matter for later). I'd like to submit my (pretty large) diffs for libpcap/DOS. But I'm a neophyte when it comes to *git* and a *pull request*. So is an email to you okay?

**Comment by guyharris** [comment]
> So is an email to you okay?

Having a repository on Github and posting a pull request from it to the libpcap repository would be best, but if you aren't set up for that yet, an email to me would be OK.

**Comment by gvanem** [comment]
Okay. I'll see what I can manage.
