### ISSUE TITLE
Output only updates every second.

### ISSUE THREAD

**Issue by rschwiet** [the-tcpdump-group/tcpdump#525]
When doing scans  and printing to display, the display updates in 1 second chunks.  Using any of the buffer change options "-U", "-l" or "--packet-buffered" seem to have no effect.  Timestamps show that all packets with the same arrival second are displayed at once.

tcpdump version 4.6.2
libpcap version 1.6.2

**Comment by guyharris** [comment]
Yes, it sets the timeout to 1 second, so, on {BPF except for AIX, Linux with TPACKET_V3, some other platforms}, the OS's packet capture mechanism waits up to 1 second for its buffer to fill up before delivering packets to libpcap and thus to the application.

`-U`/`--packet-buffered` only affect tcpdump's behavior when it's writing raw packets, in binary form, with `-w`; it does not affect its behavior when printing packets.

`-l` affects its behavior when printing dissected packets, but it affects the buffering of *output*, not *input*.

libpcap 1.7.x has an API to turn on "immediate mode", which means the OS's capture mechanism's buffering is turned off, so that it delivers packets immediately.  tcpdump 4.7.x turns immediate mode on if built with a libpcap with that API and, if it's printing dissected packets and is writing to a terminal, turns immediate mode on.

**Comment by guyharris** [comment]
As of 2cd0a90c24ccf01ad9a034d7d5a6a651c82a4785, it now sets the packet timeout to .1 second rather than 1 second if it's printing packets and either 1) it's to something a "terminal" (`isatty(1)`) or 2) it's printing a line at a time ("line-buffered" mode - `-l`). It no longer uses immediate mode unless the user asks for it with `--immediate-mode`.

That way, it still makes use of the packet buffering, which should reduce the CPU usage.
