### ISSUE TITLE
ERSPAN daemon

### ISSUE THREAD

**Issue by leonmccalla** [the-tcpdump-group/tcpdump#591]
This feature would allow tcp dump to encapulate all recieved packets for IP/gre transport to a wireshark machine.

**Comment by guyharris** [comment]
As per [this ERSPAN documentation](http://www.cisco.com/c/en/us/td/docs/switches/datacenter/sw/5_x/nx-os/system_management/configuration/guide/sm_nx_os_cg/sm_erspan.html) and [the ERSPAN I-D](https://tools.ietf.org/html/draft-foschiano-erspan-01), it's basically Yet Another Way To Send Captured Packets Over The Wire.  It uses GRE rather than, say, RPCAP over TCP or UDP.

So it sounds as if you want a way to do remote capturing, using ERSPAN, from something *other* than a Cisco switch.  That's not necessarily best done with tcpdump; it could just as easily be done with an ERSPAN daemon.  And how is ERSPAN better than any other IP-based transport here?

**Comment by leonmccalla** [comment]
you're right. Im not concerned about the encapsulation format but remote sniffing is what i need. I want to capture promiscusly from within a VirtualMachine and stream the data out to my windows desktop wireshark and I am unaware of any tools that easily do this.

Right now i have a port on the back of my esxi 5.0 server dedicated to sniffing but this port does not trully get every packet. The internal VMware switch on esxi 5.0 works for intermachine communication to an extent but some functions fail horribly and im trying to get more details.

Right now the only way i know how to sniff remotely involves installing a dedicated windows VM and rpcapd.exe. if you know of a better way please point me to the URL.

Leon

Sent from my android device.

-----Original Message-----

**Comment by alagoutte** [comment]
Hi,

Do you have look extcap "tools" from Wireshark ?

**Comment by guyharris** [comment]
> Do you have look extcap "tools" from Wireshark ?

There isn't an ERSPAN extcap tool - and it sounds as if what he needs is an ERSPAN *server* to run on the virtual machine on which he wants to capture packets, as well as needing a client.

If he wanted to use RPCAP rather than ERSPAN, then:

- if both hosts are running Windows, then, as he notes, you can use rpcapd on the machine on which he's capturing packets and Wireshark+WinPcap, which has RPCAP support, on another machine;

- if the host on which he's capturing packets isn't running Windows, he could try compiling the latest tip-of-the-master-branch libpcap, with `--enable-remote` specified, for that machine, and install the resulting rpcapd there;

- if the host on which he's running Wireshark isn't running Windows, he could try compiling the latest tip-of-the-master-branch libpcap, with `--enable-remote` specified, for that machine, install libpcap, and build Wireshark from source using that version of libpcap, and capture with that.

**Comment by alagoutte** [comment]
There is some tools like sshdump or udpdump... (using extcap)

can be help !

**Comment by gabdu** [comment]
@leonmccalla 

Did you ever get around solving this issue? My needs are exactly identical to what you described, packet sniffing on VMs (on AWS VPC) and sending the packets to a remote linux machine for offline analysis.

Everyone seems to need rpcapd but unfortunately it appears to be ill-maintained!

**Comment by leonmccalla** [comment]
No but it sounds like sshdump is needed in one of the VMs to do the sniffing for us. I work on routers and switches all day. Linux is foreign to me and Virtualization os even further away. I would not know what to do.

Leon

Sent from my android device.

-----Original Message-----

**Comment by infrastation** [comment]
From the discussion I gather that the problem can be solved using existing non-ERSPAN means, especially with the development done in rpcapd in recent years. Even if that is not the case, bringing ERSPAN into the scope of this project would be a mistake. If anybody wishes to note anything that still needs to be done before considering this issue resolved, please do that within 7 days.

**Comment by infrastation** [comment]
It is time.
