### ISSUE TITLE
Inconsistent error printing approaches

### ISSUE THREAD

**Issue by Bugcheckers** [the-tcpdump-group/tcpdump#691]
https://github.com/the-tcpdump-group/tcpdump/blob/master/tcpdump.c#L422

https://github.com/the-tcpdump-group/tcpdump/blob/master/print.c#L299

Operations on dlt_name and dltname are the same. However, 

1) the name of variables are slightly different
2) First one uses fprintf for printing errors, and the second one uses *ndo->ndo_error function.

It seems these 2 pieces of code are inconsistent.

Thanks!

**Comment by guyharris** [comment]
> the name of variables are slightly different

Yup.  Not a bug.

> First one uses fprintf for printing errors

Because it's printing output in response to a command-line request, although it should perhaps print to the standard output instead.

> and the second one uses *ndo->ndo_error function

Because it's reporting an error from a call to a "netdissect" library routine; that library produces output by calling routines specified when it was initialized.  The intent is to allow the library to be used in programs other than tcpdump, which might not necessarily report errors to the standard output or the error.

Not a bug.
