### ISSUE TITLE
need consistent tcpdump executable with each build

### ISSUE THREAD

**Issue by gavinux** [the-tcpdump-group/tcpdump#697]
we got different md5 checksum each time we build libpcap and tcpdump. It seems they depend date/time and build folder.
How can we get rid of this glitch, we need identical binary. Don't put date/time and folder name in the binary, because these date/time and build folder are not used anyway.

**Comment by guyharris** [comment]
> How can we get rid of this glitch, we need identical binary. Don't put date/time and folder name in the binary, because these date/time and build folder are not used anyway.

1) Use a compiler and linker that don't put any date/time information into object and executable file, and, if necessary, give the appropriate options to disable putting that information into the files. You're on your own finding such a toolchain for your platform, if any exist, and the options to disable that, if necessary.

2) Compile without debugging symbols, or strip the binary, so that you don't have symbol table entries giving paths to the source files.

There may be other places in your toolchain that put time stamps and paths into the object files or the executable.  You're on your own figuring out out to disable that with whatever toolchain you're using for your platform, if that's possible.

**Comment by gavinux** [comment]
thanks for the reply
$ strip -s tcpdump
works!
