### ISSUE TITLE
move struct ether_header from .c to .h

### ISSUE THREAD

**Issue by XhstormR** [the-tcpdump-group/tcpdump#714]
I am writing a program about the network recently.

I reference some of the header files in this project to define the structure of some network packets, like ip header、tcp header, but the ethernet header structure  are in the .c file, so I have to compile tcpdump, otherwise it will fail to compile.

Is it possible to move this structure to the header file?

https://github.com/the-tcpdump-group/tcpdump/blob/1c30d69b979624733af5cbd2dd9653b609584e6f/print-ether.c#L35-L105

**Comment by infrastation** [comment]
Only `print-ether.c` uses the `ether_header` structure, hence the structure is in that file only and not in a shared header file. This is the current code style convention in tcpdump introduced in commit 27d428c. It would be wrong to change this to accommodate your project. Your project can use the headers that come with the OS, for instance, in Linux this same declaration is available from `/usr/include/net/ethernet.h`; or it can just have its own declaration. Closing.

**Comment by guyharris** [comment]
> I reference some of the header files in this project to define the structure of some network packets, like ip header、tcp header, but the ethernet header structure are in the .c file, so I have to compile tcpdump, otherwise it will fail to compile.

tcpdump *itself* used to get some packet header information, such as the IP and TCP headers, from operating system include files.

This was more trouble than it was worth, because those include files differed from OS to OS and, for example, 1) the HP-UX version of include file used for DNS headers didn't define everything that our DNS dissector needed and 2) there wee some issues with the Tru64 UNIX headers.

So we just took headers from various \*BSDs, modified them to match our needs, and added them to the tcpdump source.

I suggest that you define the structures yourself in your program, just as we do in tcpdump.

**Comment by XhstormR** [comment]
Thank you for your suggestion.
