### ISSUE TITLE
How to filter http hostname

### ISSUE THREAD

**Issue by liudonghua123** [the-tcpdump-group/tcpdump#737]
I get to know how can I filter GET/POST packets via `tcpdump -s 0 -A 'tcp[((tcp[12:1] & 0xf0) >> 2):4] = 0x47455420'`/`tcpdump -s 0 -A 'tcp[((tcp[12:1] & 0xf0) >> 2):4] = 0x504f5354'` (http://www.music-come.com/2015/06/09/tcpdump-http-request/, https://security.stackexchange.com/questions/121011/wireshark-tcp-filter-tcptcp121-0xf0-24). 
However I want to filter by host header of http request, which the position in tcp depend on the previous http header and its length vary, does tcpdump support filter like `http.host contains "www.grs.ynu.edu.cn"` like whireshark does, or `tcp contains www.grs.ynu.edu.cn`.

**Comment by infrastation** [comment]
Recent versions of tcpdump display the ASCII payload of TCP for plain text based protocols such as HTTP, SMTP, POP3 etc. when run as `tcpdump -v` (a useful feature added by Guy Harris), but that payload isn't parsed or otherwise involved in packet filtering. If Wireshark allows to filter based on HTTP headers, that would be the solution for your project.
