### ISSUE TITLE
tcpdump - Exact code segement where user defined port number is checked

### ISSUE THREAD

**Issue by Norman03** [the-tcpdump-group/tcpdump#803]
I have downloaded the latest tcpdump from github master and compiled and built the same. Then I'am able to run the tcpdump binary. My goal is to filter the packets from port "80" and I'm able to do using below command. Now I need insert few code sections in tcpdump when port "80" check is passed for every frames. Now I'm not able to find code segment where the exact port check for every frames is done. So that I can insert my code sections.

`sudo ./tcpdump -i eth0 port 80`

```
tcpdump version 4.10.0-PRE-GIT
libpcap version 1.8.1
```

**Comment by guyharris** [comment]
It's in libpcap, not in tcpdump.

tcpdump calls `pcap_compile()`, passing it the filter string; `pcap_compile()` attempts to convert that into a program in a pseudo-machine language.  See ["The BSD Packet Filter: A New Architecture for User-level Packet Capture"](https://www.tcpdump.org/papers/bpf-usenix93.pdf).

If `pcap_compile()` succeeds, tcpdump passes the compiled code to `pcap_setfilter()` to make the it be the filter for the capture.

On most platforms, that filter code is passed by libpcap into OS kernel-mode code, and interpreted there.  If that fails due to the filter being too large, or if it uses loops (as required by the `protochain` term in a filter expression), the filter has to be interpreted in the filter interpreter in libpcap.

**Comment by Norman03** [comment]
@guyharris If that so, to insert my code sections I have to do it in libpcap?

**Comment by guyharris** [comment]
> @guyharris If that so, to insert my code sections I have to do it in libpcap?

If you want to change what a filter of "port 80" does, you will have to change the BPF code that `pcap_compile()` generates, and `pcap_compile()` is in libpcap, so, yes, you would have to change the BPF compiler in libpcap.

> If this is the case,could you help providing the exact steps to do it?

Yes, if 1) you file an issue in the [libpcap issue section](https://github.com/the-tcpdump-group/libpcap/issues) and 2) you say *precisely* what you're trying to do.  I won't provide any help in the tcpdump issue section, as it's not a tcpdump issue; I'll only provide help if you file a libpcap issue *and* give precise details on what you're trying to do.
