### ISSUE TITLE
'make check' gives : "cat: .failed: No such file or directory"

### ISSUE THREAD

**Issue by fxlb** [the-tcpdump-group/tcpdump#820]
With current master:
```
Running tests from /home/cpe/soft-origin/tcpdump/my-tcpdump/tests
Running /home/cpe/soft-origin/tcpdump/my-tcpdump/tests/crypto.sh
cat: .failed: No such file or directory
```

**Comment by guyharris** [comment]
For now, we still need to create and initialize the `.passed` and `.failed` files in the top-level script, because we still have shell scripts that use them as "global variables" to allow a global count of test successes and failures in all the scripts.

Once we no longer have any shell scripts, we can eliminate them.

(But I need to fix TESTrun to *read* those files and add the results to its count of successes and failures; I'll do that next.)

**Comment by guyharris** [comment]
So I added code to initialize the files in 6426ddfb52a84b777f4d974de87871f24d8d146f and added code to read them and add the contents to the pass and fail counts in 0069f1d9f8aca26b165a07d6da7b162d00d24209.

**Comment by mcr** [comment]
Guy Harris <notifications@github.com> wrote:
    > (But I need to fix TESTrun to *read* those files and add the results to
    > its count of successes and failures; I'll do that next.)

Please don't do this... the count is not that important for the moment.
let's just suffer without that count for a day or two.
