### ISSUE TITLE
configure uses system libpcap even if there's a libpcap in ../libpcap

### ISSUE THREAD

**Issue by fxlb** [the-tcpdump-group/tcpdump#823]
Debian bullseye (testing)
Local pcap library installed in ../libpcap
Bug ?
```
./configure --with-system-libpcap 2>&1|tee with-system-libpcap; make -s clean all; ./tcpdump --version
tcpdump version 4.10.0-PRE-GIT
libpcap version 1.9.1 (with TPACKET_V3)
OpenSSL 1.1.1d  10 Sep 2019
SMI-library: 0.4.8
```
```
./configure --without-system-libpcap 2>&1|tee without-system-libpcap; make -s clean all; ./tcpdump --version
tcpdump version 4.10.0-PRE-GIT
libpcap version 1.9.1 (with TPACKET_V3)
OpenSSL 1.1.1d  10 Sep 2019
SMI-library: 0.4.8
```
```
diff with-system-libpcap without-system-libpcap
<EMPTY>
```

**Comment by guyharris** [comment]
The name of the option is really bogus.

The purpose of the option is, apparently, to suppress the check for the local pcap library, where "local" means "in ../libpcap"  - it should still check in /usr *and* /usr/local.

And the implementation is incorrect - it treats `--with-system-libpcap` and `--without-system-libpcap` as the same.

Perhaps we should, instead, have a `--enable-local-libpcap` option, which is the default, so that:

- with neither `--enable-local-libpcap` nor `--disable-local-libpcap`, it looks first for a local libpcap;
 - with `--enable-local-libpcap`, it looks first for a local libpcap;
 - with `--disable-local-libpcap`, it *doesn't* look first for a local libpcap.

**Comment by fxlb** [comment]
This looks good.

**Comment by mcr** [comment]
And I don't see anything in cmake to do the same...

**Comment by guyharris** [comment]
> And I don't see anything in cmake to do the same...

Currently, the "local libpcap" assumes that the libpcap build directory is a subdirectory of the same directory as the tcpdump build directory; that's commonly the case, although it's not guaranteed to be the case.  For example, if the build directory is the source directory, if you've unpacked the libpcap and tcpdump source into directories in the same directory, which I think is a fairly common case, that's true.

For CMake, I think a common convention is to build in a "build" directory that's a subdirectory of the source directory (that's the way I've been doing CMake builds), in which case libpcap binaries wouldn't be in ../libpcap*, it'd be in ../../libpcap*/build.  In addition, building in a build directory that's a subdirectory of the same directory as the source directory might be common as well.

So I punted and didn't add "local libpcap" support to CMake.  Any ideas?

**Comment by guyharris** [comment]
So, with daff285ecf3cc42769075aa97b072116b9494494, does configure:

- find a local libpcap, if present, by default;
- use only an installed libpcap if `--disable-local-libpcap` is specified?

And does that resolve the problem you're seeing?

**Comment by fxlb** [comment]
Yes, thank you.
