### ISSUE TITLE
make depend is broken

### ISSUE THREAD

**Issue by mcr** [the-tcpdump-group/tcpdump#841]
Somewhere along the way we have broken "make depend"

**Comment by guyharris** [comment]
It works for me with a freshly pulled tcpdump from the master branch, on macOS 10.15.3 with the current Xcode's compilers.

On what platform is this failing?

Travis *is* reporting a *compile* error when building with -Werror for pull request #838, but that's different.

**Comment by mcr** [comment]
Guy Harris <notifications@github.com> wrote:
    > It works for me with a freshly pulled tcpdump from the master branch,
    > on macOS 10.15.3 with the current Xcode's compilers.

    > On what platform is this failing?

linux, debian/ubuntu.
It fails to find the ./mkdep, and the resulting Makefile is wrong.
Are you using ./configure or cmake?

**Comment by guyharris** [comment]
> Guy Harris <notifications@github.com> wrote: It works for me with a freshly pulled tcpdump from the master branch, on macOS 10.15.3 with the current Xcode's compilers. On what platform is this failing?
> linux, debian/ubuntu.

OK, I can try it on my Ubuntu 18.04 VM; what version of Debian/Ubuntu are you using?

> It fails to find the ./mkdep, and the resulting Makefile is wrong. Are you using ./configure or cmake?

I'm using ./configure; with CMake, CMake does its own dependency management, so there's no need for "make depend" or the mkdep program.

Are *you* using ./configure with an out-of-source-tree build?  If it's looking in the current directory, rather than the source directory, that won't work.  I tried an out-of-tree build, and it failed in the configure stage, but the problem wasn't that it failed to find mkdep - it found it, because it looked in the source directory - but the script looked in the current directory for the source files.  I'll look at that (and check it for libpcap as well).

**Comment by mcr** [comment]
I'm using devuan ascii on my desktop.  I'm doing an in-tree ./configure, because cmake doesn't do libpcap-is-adjacent, and I need that for now.

**Comment by guyharris** [comment]
It worked for me on Ubuntu 18.04; what issues are you seeing?  (You *do* have a .devel file in the top-level source directory, right?)

**Comment by mcr** [comment]
Guy Harris <notifications@github.com> wrote:
    > It worked for me on Ubuntu 18.04; what issues are you seeing?  (You
    > *do* have a .devel file in the top-level source directory, right?)

Maybe that's what I'm missing. Oops.
That just kinda stays there over the decade...

**Comment by fxlb** [comment]
Can we close ?
