### ISSUE TITLE
tcp-push not working on filtering when analyzing pcap from 2013

### ISSUE THREAD

**Issue by pninjagrodd** [the-tcpdump-group/tcpdump#846]
Greetings,

It seems that the tcpdump version 4.9.3 has a bug when it is declared a filter directly to the tcp-push flag by using tcpflags on a pcap from 2013:

`tcpdump 'tcp[tcpflags] == (tcp-push)' -r filefrom2013.pcap`

This command does not returns any output. 

But, if I declare the filter as:
`tcpdump 'tcp[tcpflags] & (tcp-push) != 0' -r filefrom2013.pcap`
or
`tcpdump 'tcp[13] == 8' -r filefrom2013.pcacp`

It executes the filtering flawlessly, showing only the selcted PUSH packets. Does anyone knows why is this happening?

In addition, I've seen many tutorials and even some man files that still includes the PUSH flag as "tcp-psh" when currently is specified as "tcp-push".

Thanks and stay safe!

Pi-Ninja

tcpdump version 4.9.3
libpcap version 1.9.1 (with TPACKET_V3)
OpenSSL 1.1.1d  10 Sep 2019

**Comment by fxlb** [comment]
Are those packets flags `push + ack` ?

**Comment by fxlb** [comment]
> In addition, I've seen many tutorials and even some man files that still includes the PUSH flag as "tcp-psh" when currently is specified as "tcp-push"

They are wrong. It's `tcp-push` since at least 1999.

**Comment by guyharris** [comment]
> `tcpdump 'tcp[tcpflags] == (tcp-push)' -r filefrom2013.pcap`
> 
> This command does not returns any output.
> 
> But, if I declare the filter as:
> `tcpdump 'tcp[tcpflags] & (tcp-push) != 0' -r filefrom2013.pcap`
> or
> `tcpdump 'tcp[13] == 8' -r filefrom2013.pcacp`
> 
> It executes the filtering flawlessly, showing only the selcted PUSH packets. Does anyone knows why is this happening?

As @fxlb notes, those are two different filters, and should be expected to behave differently.

The first filter is "the only flag that's set is PSH", meaning that a packet with PSH+ACK will *NOT* be matched.  Once a TCP connection is established, just about *every* packet has ACK set, so that filter will probably match only the initial SYN.

The second filter is "the PSH flag is set", meaning that a packet with PSH+ACK *will* be matched.

**Comment by pninjagrodd** [comment]
Thank you for your replies!
So, if I want to filter only to PSH packets, the only command I should use is this one right?
`tcpdump 'tcp[tcpflags] == (tcp-push)' -r filefrom2013.pcap`

**Comment by guyharris** [comment]
> Thank you for your replies!
> So, if I want to filter only to PSH packets, the only command I should use is this one right?
> `tcpdump 'tcp[tcpflags] == (tcp-push)' -r filefrom2013.pcap`

What do you mean by "filter only to PSH packets"?

If you mean "filter so I see only packets that have PSH as the ***ONLY*** flag set in the TCP header - not ACK, *anything* - the command you should use is

    tcpdump 'tcp[tcpflags] == (tcp-push)' -r filefrom2013.pcap

You won't see many packets with that, however.

If you mean "filter so that I see only packets that have PSH set in the TCP header" - including packets with other flags, such as ACK, set - the command you should use is

    tcpdump 'tcp[tcpflags] & (tcp-push) != 0' -r filefrom2013.pcap

You'll see more packets with that.

I'm skeptical that

    tcpdump 'tcp[13] == 8' -r filefrom2013.pcap

worked for you, as that *also* tests whether PSH is the only flag set; a working filter would be

    tcpdump 'tcp[13] & 8 != 0 -r filefrom2013.pcap

**Comment by pninjagrodd** [comment]
That's exactly what I was meaning. I am very appreciated for your great insight in this topic.
