### ISSUE TITLE
Please make new release

### ISSUE THREAD

**Issue by kloczek** [the-tcpdump-group/tcpdump#869]
In repo is already almost 2k commits since last release.

Really it woild be better to make a bit more frequent release.

**Comment by fenner** [comment]
We ship tcpdump 4.9.3 with our product, since the overhead of answering the question "if a security problem is reported, is it applicable to this random git snapshot I grabbed" is too high.  This means that when we develop patches, they're based on the `EXTRACT_` macros, with `TCHECK_`, etc. and need to be ported to the style that's in master.  The current state of affairs is doubling the amount of work for vendors to develop tcpdump.  (And, frankly, demotivating.)

**Comment by mcr** [comment]
I've been working on tcpdump 4.10 in the past week.
Opening a ticket, rather than closing other tickets isn't helping me do that
:-)

**Comment by kloczek** [comment]
BTW on new releasese it would be good consider change tagging converntion. Current one `tcpdump-<version>` is causing that autogenerated tar ball like https://github.com/the-tcpdump-group/tcpdump/archive/tcpdump-4.9.3.tar.gz has `tcpdump-tcpdump-4.9.3/` base direcory inside because gitlab/github automatically adds reponame as prefix to that base directory.

This woiuld be really welcome on automated packaging and testing.

**Comment by infrastation** [comment]
@fenner, you have a good point, please try to understand that life may be difficult for other people too. There is indeed a problem, let's see how it can be solved or reduced.

@kloczek, auto-generated tarballs for tags (which they present as "releases" without a good reason) is a feature that GitHub users can neither disable nor configure, and the behaviour can change at any time, so it would not be right to spin the world around it and to break the naming conventions established in this project. The contents of these downloads is just the output of `git archive`, if you do need exactly that, you can get that directly from a local git clone. If you expect to download a tarball from a known location and to find a known directory structure in it, it would be more appropriate to use the tarballs from www.tcpdump.org, the contents of these tarballs is a result of `make releasetar`.

**Comment by kloczek** [comment]
> @kloczek, auto-generated tarballs for tags (which they present as "releases" without a good reason) is a feature that GitHub users can neither disable nor configure, and the behaviour can change at any time, so it would not be right to spin the world around it and to break the naming conventions established in this project.

It is not rocket science to just execute "autoreconf -fiv" and then continue normal build procedure. Issue is that official dist tart ball do not provide exactly the same state ass it is in git so applying some git patches on top of the dist tar balls in many cases simple fails. Only way to avoid that is to bend packages build procedure to use autogenerated by git tar balls.
Also please do not bother about packaging layer issue. Just provide well defined interface for anyone who operates outside of your normal activity area. Crucial part of that interface is provide **predictable** new version git tag in case of projects maintained in git repos.

One time tagged repo should not be retagged. So far nothing happened so you don't need to take care something like that.
The same should be with dist tar balls.
I have automation which collects used on packaging layer checksums of downloaded tar balls. For me change of that checksum it is clear warning that original repo was compromised and the same approach is using may other people operating on area of packaging the software.

One more time. Please do not try to solve any packaging layer possible "problems" because as person which is more or mainly working as developer you have high chance to disturb than help solve something. Just please do only what you can do the best .. only this and nothing more. You don't need to solve Earth famine problems using git :)

Regards

**Comment by fenner** [comment]
On Mon, Aug 31, 2020 at 7:26 AM Denis Ovsienko <notifications@github.com>
wrote:

> @fenner <https://github.com/fenner>, you have a good point, please try to
> understand that life may be difficult for other people too. There is indeed
> a problem, let's see how it can be solved or reduced.
>

Yes, I'm very familiar with the release engineering problem. My first
software release that failed to (ever!) materialize because it had a vague
goal and kept accruing features was in 1998.

My sense of today's solution to this problem is to release more often.
This of course feels upside down, we are trying to get a release ready and
it is so much work, how can we solve the problem by doing more work? But
the key difference when releasing often is: nothing must desperately make
this release, because there will be another one soon.  All of a sudden you
can make a release with all the GET_* changes, but maybe without all
problems fixed - because another release is coming in a couple of months
(instead of a couple of years).  Yeah, 4.10.0 in September has some
compiler warnings when you build on Solaris, so those will be fixed in
4.10.1 in November. And there are some big-picture issues that won't be
fixed in 4.10.1 either, but maybe the work will progress and 4.10.2 in
January will have it.

  Bill

**Comment by mcr** [comment]
yes, I'm trying to increase the release cadence.

The question isn't really how to release, the question is what to push
forward.  But, you are right, the TCHECK, etc. patches are overdue.

--
]               Never tell me the odds!                 | ipv6 mesh networks [
]   Michael Richardson, Sandelman Software Works        |    IoT architect   [
]     mcr@sandelman.ca  http://www.sandelman.ca/        |   ruby on rails    [

**Comment by fxlb** [comment]
It's to soon for a 4.10, setjmp/longjmp work need update.

**Comment by infrastation** [comment]
It will take some time to make the code ready because it is one of the biggest changes in the code base and it is not complete yet. Please have the patience.

**Comment by fxlb** [comment]
More information here:
https://lists.sandelman.ca/pipermail/tcpdump-workers/2020-September/001508.html

**Comment by kloczek** [comment]
Just kind of advice.
In the future if you will be working on some similar large scale changes it is good to do that as PR or separated branch because if  someone will submit some critical patch in the middle of such work it would be not possible to make new release out of current master tree.
As well it will allow make new releases a bit more schedule able as master could be easier to keep in kind of clean form.

Thx for your work :)

**Comment by infrastation** [comment]
The matter is, in this particular software releases do not come from the master branch. But there is no point in arguing, there's work that needs to be done, and before it is done the code is not ready in the first place, however many ceremonies you put around it.

**Comment by fenner** [comment]
> We ship tcpdump 4.9.3 with our product, since the overhead of answering the question "if a security problem is reported, is it applicable to this random git snapshot I grabbed" is too high. This means that when we develop patches, they're based on the `EXTRACT_` macros, with `TCHECK_`, etc. and need to be ported to the style that's in master. The current state of affairs is doubling the amount of work for vendors to develop tcpdump. (And, frankly, demotivating.)

I experienced a massive demotivation yesterday.  A colleague asked me about getting macsec printing into our tcpdump.  He looked it up and it was committed to master in 25576378 - in 2017.  Luckily since it was committed *so* long ago, that code is fairly compatible with 4.9.x, so there's a straightforward answer to how we can have it in our version.  But it reminded me of all of the *other* improvements that are stuck in limbo.

I know that me being upset doesn't change anything about your ability to work on the project.  But it's still relevant.

**Comment by infrastation** [comment]
If you have time and energy to spend on making this problem smaller and would like me to talk you through possible ways of doing it, feel free to reach me directly.

**Comment by Neustradamus** [comment]
From my https://github.com/the-tcpdump-group/tcpdump/issues/892:

Dear tcpdump team,

When the new build will be here?

Last build:
- https://www.tcpdump.org/
- Version: 4.9.3
- Release Date: September 30, 2019

There is a CVE in 4.9.3:
- https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-8037

And there was in 4.10 git pre version:
- https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-8036

Thanks.

**Comment by chenrui333** [comment]
Is `tcpdump-4.99.0` the new release? That version number seems a bit confusing. Thanks!

**Comment by fxlb** [comment]
Yes, it is. The goal was to do a 5.0.0 release (with setjmp/longjmp logic).
Il will take a few months more to achieve this.
4.10.0 release number would have been unrelevant with more than 2000 commits since 4.9.3.
See : https://lists.sandelman.ca/pipermail/tcpdump-workers/2020-December/001569.html

**Comment by chenrui333** [comment]
@fxlb appreciate the confirmation, but really we should stick with the semver even though it has been too many developments since last release. Just my two cents. :)

**Comment by Neustradamus** [comment]
Warning: Debian 11 freeze is 2021-01-12, please release the next version before.
Next Debian will be in 2023.

cc @rfrancoise.

**Comment by Neustradamus** [comment]
Warning: Debian 11 freeze is 2021-01-12, please release the next version before.
Next Debian will be in 2023.
cc @rfrancoise.

Note to @rfrancoise: There is already a new Libpcap version: https://github.com/the-tcpdump-group/libpcap/tags.

**Comment by rfrancoise** [comment]
Yes, I'm aware of the new releases, thanks.

**Comment by guyharris** [comment]
[4.99.0 is now available](https://www.tcpdump.org/index.html#latest-releases).

**Comment by kloczek** [comment]
And again it would be good to have new release as https://github.com/the-tcpdump-group/tcpdump/compare/tcpdump-4.99.1...master shows +470 vomits.
Really smaller batches of commits in every release allows spot some issues introduced in that batch.
Whit such beg volume of the commits like it is in tcpdump I would recommend to make releases every month.

I know that you are busy but I would ask you to make releases a bit more frequently 😋 
Please ..
