### ISSUE TITLE
Tcpdump:  two problem, reading pcap file and capture  bgp update info

### ISSUE THREAD

**Issue by carboxste** [the-tcpdump-group/tcpdump#885]
If I  need to capture some nets received by bgp remote speaker when bgp session starts.
I can create the pcap file:

tcpdump -S0 -i "interface" host "remote neighbor" -w file.pcap.

I open the pcap file with Wireshark and I can see all frames containing all 817000 downloaded nets (full routing table received from the remote carrier's speaker)
After the full routing, I can see  all following update bgp information (UPDATE AS-PATH, withdrawn and so on).

Perfect.

The first problem is that I am not able to use tcpdump like wireshark to read the pcap file.
There are no options with tcpdump to read the pcap file and capture one or more network of full routing table.

Wireshark wotks fine, tcpdump dont.

If I want to capture in real time bgp updates information it's not a problem.
Simply I can launch

 /usr/sbin/tcpdump -f -s 0 -i "interface" -nn -N -S -vvv -tttt port bgp and src host "remote speaker address"

and I obptain the information, for example these:

        Update Message (2), length: 74
          Origin (1), length: 1, Flags [T]: Incomplete
            0x0000:  02
          AS Path (2), length: 22, Flags [T]: 3269 6762 6453 4761 4795 
            0x0000:  0205 0000 0cc5 0000 1a6a 0000 1935 0000
            0x0010:  1299 0000 12bb
          Next Hop (3), length: 4, Flags [T]: 62.86.118.243
            0x0000:  3e56 76f3
          Community (8), length: 8, Flags [OT]: 6762:30, 6762:13300
            0x0000:  1a6a 001e 1a6a 33f4
          Updated routes:
            202.155.148.0/24

The second problem is that, if I shut down the ebgp session, I launch the tcpdump string and then I start the bgp session again,
the tcpdump does not capture the full routing tables net received.

Trust me the problem is true.
I work on ISP provider and manage a lot of ebgp session for customers.

Thank you
Regards
Stefano

**Comment by infrastation** [comment]
Thank you for the file. From the packets it is easier to see that the two BGP peers exchange UPDATE messages, some of which are too big to fit into a single TCP packet, so they become split over several packets. Specifically, your network of interest is in an UPDATE message that is 1665 bytes long. If you save just the packet 27 as suggested above, Wireshark will not be able to decode it because it starts in the middle of a BGP message. When the previous packets are available, Wireshark reassembles the TCP segments and displays the recovered BGP UPDATE at packet 27, which is the last packet, but likewise it could display it at the first packet. tcpdump never reassembles TCP segments, this is unlikely to improve.

In addition to that, the current BGP implementation in tcpdump does not decode BGP messages that were not entirely captured in a packet. Somebody may improve that in future to print the fist incomplete part of such messages. This is doable, for some other protocols that is already done. But of course that again would not print your network of interest if it happens to be in a subsequent packet with the rest of the UPDATE message, so it would not be a reliable solution even if it is implemented.

If you need reliable results in this use case, Wireshark/tshark indeed would be the right tool.

**Comment by carboxste** [comment]
David, it's all clear.

Thank you for the support.


Regards
Stefano
