### ISSUE TITLE
Print the tcpdump and libpcap version strings, print a usage message, and exit.

### ISSUE THREAD

**Issue by timoren** [the-tcpdump-group/tcpdump#887]
Hi,  I'm trying to get a version of tcpdump and libpcap, but the output of the command redirected to stderr.
host details:
Red Hat Enterprise Linux Server release 7.8

print screen:
[root@tested ~]# tcpdump -h > /tmp/tcpdump_output 2> /tmp/tcpdump_error
[root@tested ~]# cat /tmp/tcpdump_output
[root@tested ~]# cat /tmp/tcpdump_error 
tcpdump version 4.5.0-PRE-GIT_2020_10_25
libpcap version 1.10.0-PRE-GIT (with TPACKET_V3)
Usage: tcpdump [-aAbdDefhHIJKlLnNOpqRStuUvxX] [ -B size ] [ -c count ]
		[ -C file_size ] [ -E algo:secret ] [ -F file ] [ -G seconds ]
		[ -i interface ] [ -j tstamptype ] [ -M secret ]
		[ -P in|out|inout ]
		[ -r file ] [ -s snaplen ] [ -T type ] [ -V file ] [ -w file ]
		[ -W filecount ] [ -y datalinktype ] [ -z command ]
		[ -Z user ] [ expression ]
[root@tested ~]# 

* there is the same issue with tcpdump version 4.9.3

**Comment by infrastation** [comment]
It had been like this for a long time until recently. The master branch since commit 49894b4 prints usage and version to standard output when the user explicitly requests this information. Please mind that it will take time until this change of behaviour propagates even after the next release, so you can work around the traditional behaviour and/or build tcpdump from the master branch and use it and/or backport the commit into old version if that makes sense to you.

**Comment by infrastation** [comment]
Closing as resolved.
