### ISSUE TITLE
Locale error in print-802_11.c

### ISSUE THREAD

**Issue by gvanem** [the-tcpdump-group/tcpdump#929]
The tests `802.11_exthdr` and `802.11_rx-stbc` causes lots of differences in the rate-values 
when the numeric locale is not `"en-US"`. Caused by :
```c
#define PRINT_RATE(_sep, _r, _suf) \
	ND_PRINT("%s%2.1f%s", _sep, (.5 * ((_r) & 0x7f)), _suf)
```

Like when I do (in `tests`):
```
..\windump.exe -nr ieee802.11_exthdr.pcap

reading from file ieee802.11_exthdr.pcap, link-type IEEE802_11_RADIO (802.11 plus radiotap header), snapshot length 65535
14:59:13.707778 10016360us tsft 1.0 Mb/s 2412 MHz 11b -22dBm signal -86dBm noise antenna 1 [bit 32] Probe Request (omus)
 [1,0 2,0 5,5 11,0 6,0 9,0 12,0 18,0 Mbit]
```

But all these trailing rates in `ieee802.11_exthdr.out` are with dots (`.`).

Adding a `setlocale (LC_NUMERIC, "en-US");` in `tcpdump.c` fixes this issue.

I see the `ieee802.11_exthdr.*` files has not been changed for a long time.
But this issue is more recent; no problem with these tests 2 months ago.

**Comment by guyharris** [comment]
For tests, we should probably set the locale to en-US, just as we set TZ.

> Adding a `setlocale (LC_NUMERIC, "en-US");` in `tcpdump.c` fixes this issue.

As would, I think, `setlocale (LC_NUMERIC, "C");`, and the latter would avoid the "America, \*\*\*\* yeah!" of which the former carries a bit of a whiff. :-)

> I see the ieee802.11_exthdr.* files has not been changed for a long time.
> But this issue is more recent; no problem with these tests 2 months ago.

That's odd.  `ND_PRINT()` ends up calling a printf-family routine in tcpdump, and I'd expect %2.1f not to have changed its behavior in the past couple of months.

I'd have to read the C90 or C99 spec in a bit of detail to figure out what it says about the effect of the locale setting on the output; I *think* it's supposed to use the locale's decimal separator, but I'm not sure.

In any case, this is output being sent to humans, so I'd say it should probably use the locale's decimal separator.  At least if you're using a shell that lets you set an environment variable in a per-process fashion, e.g. all Bourne-compatible shells, if the output is intended for a program that's expecting periods as decimal separators, it can be run with `LC_NUMERIC=C`.

**Comment by gvanem** [comment]
> As would, I think, setlocale (LC_NUMERIC, "C");

Yes, that works too. Gives ` [1.0 2.0 5.5 11.0 6.0 9.0 12.0 18.0 Mbit]`.

> ... so I'd say it should probably use the locale's decimal separator. 

Agreed. But for the sake of all tests passing, could there be some code to fix this?
A `set LC_NUMERIC=C` has no effect on Windows. So could we do:
```c
  const char *lc_numeric = getenv("LC_NUMERIC");
  if (lc_numeric)
     setlocale(LC_NUMERIC, lc_numeric);
```

**Comment by guyharris** [comment]
>     14:59:13.707778 10016360us tsft 1.0 Mb/s 2412 MHz 11b -22dBm signal -86dBm noise antenna 1 [bit 32] Probe Request (omus)
 [1,0 2,0 5,5 11,0 6,0 9,0 12,0 18,0 Mbit]

So why is the rate from the radiotap header "1.0 Mb/s", with a period, while the rates from the Supported Rates IE in the packet show rates such as "1,0", with a comma?  They're *both* printed with %2.1f".

Perhaps something's getting smashed in the C runtime's data structure, so it switches from . to , midstream?

**Comment by guyharris** [comment]
Which source is this built from? Tip-of-main-branch tcpdump?  And what toolchain and C library is being used?

**Comment by guyharris** [comment]
So I whipped up a small test program, decsep.c (DECimal Separator):

```
#include <stdio.h>
#include <locale.h>

int
main(int argc, char **argv)
{
	if (argc == 2)
		setlocale(LC_NUMERIC, argv[1]);
	printf("%2.1f\n", 5.5);
	return 0;
}
```

Compiled on macOS, and run with various arguments and environment variable settings, I get:

```
macos$ ./decsep
5.5
macos$ ./decsep fr_FR
5,5
macos$ ./decsep ""
5.5
macos$ LANG=fr_FR ./decsep ""
5,5
macos$ LANG=fr_FR ./decsep "C"
5.5
```

so it appears to default to the C locale, in which "." is the decimal separator; if you call `setlocale()` with an empty string, it picks up the local from "the system" (from the LANG or LC_ environment variables, in the case of UN\*Xes).

On Windows 20, compiled with the MSVC and C library versions as of my last update of Visual Studio, I get:

```
C:\Users\guy>.\decsep
5.5

C:\Users\guy>.\decsep C
5.5

C:\Users\guy>.\decsep fr-FR
5,5

C:\Users\guy>.\decsep fr_FR
5,5

C:\Users\guy>set LANG=fr-FR

C:\Users\guy>.\decsep
5.5

C:\Users\guy>.\decsep ""
5.5

C:\Users\guy>.\decsep "C"
5.5
```

So the `LANG` environment variable does *not* appear to affect the library's behavior.

What C90 says about `setlocale()` is:

> The **`setlocale`** function selects the appropriate portion of the program’s locale as specified by the **`category`** and **`locale`** arguments. The **`setlocale`** function may be used to change or query the program’s entire current locale or portions thereof. The value **`LC_ALL`** for category names the program’s entire locale; the other values for category name only a portion of the program’s locale. **`LC_COLLATE`** affects the behavior of the **`strcoll`** and **`strxfrm`** functions. **`LC_CTYPE`** affects the behavior of the character handling functions and the multibyte functions. **`LC_MONETARY`** affects the monetary formatting information returned by the **`localeconv`** function. **`LC_NUMERIC`** affects the decimal-point character for the formatted input/output functions and the string conversion functions, as well as the nonmonetary formatting information returned by the **`localeconv`** function. **`LC_TIME`** affects the behavior of the **`strftime`** function.
> 
> A value of **`"C"`** for **`locale`** specifies the minimal environment for C translation; a value of **`""`** for locale specifies the implementation-defined native environment. Other implementation-defined strings may be passed as the second argument to **`setlocale`**.
> 
> At program startup, the equivalent of
> 
> **`setlocale(LC_ALL, "C");`**
> 
>  is executed.
> 
> The implementation shall behave as if no library function calls the **`setlocale`** function.

So:

1. The C standard doesn't say that environment variables affect the locale, even though it *does* have the notion of environment variables and has a `getenv()` function;
2. calling `setlocale(LC_ALL, "C")` at the beginning of a program should make no difference to the program's behavior;
3. no library function should visibly change the locale setting.

Given 1), "A `set LC_NUMERIC=C` has no effect on Windows." isn't forbidden by C90.

Given 2), I'm not sure why calling `setlocale(LC_ALL, "en-US")` should make a difference, either, unless some implementation's C locale allows the decimal-point character to change; unless I missed something, C90 doesn't indicate what the C locale looks like ("minimal environment for C translation" doesn't seem to be defined anywhere I could find).

Given 3), nothing should be changing the local out from under tcpdump while it's printing a packet.

[The `setlocale()` page in Microsoft Docs](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/setlocale-wsetlocale?view=msvc-160) gives a lot of details on how the locale is set, but mentions nothing about environment variables, so they shouldn't affect the locale.  `setlocale( LC_ALL, "" )` sets the locale name to the value returned by `GetUserDefaultLocaleName()`.

I'll have to try setting my locale to French on my Windows 10 VM and run `.\decsep "C"` to see which decimal-point character is used.

None of this explains why different decimal-point characters are used *for the same packet*, as per may earlier comment.

**Comment by guyharris** [comment]
OK, if I set the regional format on my Windows VM to "French (France)" and set the display language to French, I get:

```
C:\Users\guy>.\decsep
5.5

C:\Users\guy>.\decsep "C"
5.5

C:\Users\guy>.\decsep ""
5,5
```

so it appears that the C locale is the default if you don't call `setlocale()`, and has "." as its decimal-point character.  If you specify a locale of `""`, to select the default locale, that locale, with those settings, has "," as its decimal-point character.

**Comment by gvanem** [comment]
> Perhaps something's getting smashed in the C runtime's data structure, 

That was a copy-paste error of mine; they're all printed with `,`.

> Which source is this built from? Tip-of-main-branch tcpdump? 

Yes. And with MSVC/clang-cl on Windows 10.

**Comment by guyharris** [comment]
> > Tip-of-main-branch tcpdump?
> Yes.

So presumably you changed something to arrange that the executable be called "windump.exe" rather than the default "tcpdump.exe".

> MSVC/clang-cl on Windows 10.

I built it with MSVC/Microsoft's-front-end-and-code-generator on Windows 10, set the region to France and the regional format to "France (French)", and ran the tests (`msbuild check.vcxproj ` in the `build` directory), and the `802.11_exthdr` test passed.

Perhaps I need to set other items, or perhaps I should use a different region, e.g. Norway.

Does MSVC/clang-cl use the same run-time library as MSVC/Microsoft's-front-end-and-code-generator?  Or does it use a different library?  (I'm assuming that the "when the program starts, it behaves as if `setlocale(LC_ALL, "C")`", and the behavior of `fprintf()` with respect to the decimal-point character is controlled by the run-time library, not by the C parser or code generator.)

**Comment by guyharris** [comment]
By the way, what happens if you compile my small test program (which I'm attaching) with MSVC/clang-c and try the tests I did with the version compiled with MSVC/Microsoft's-front-end-and-code-generator?  (It's called "decsep.c.txt" because GitHub is stupid and "[doesn't] support that file type".

Hello, GitHub, you *do* realize that people *do* store *C language source code* on this site, and report bugs with *C language source code*, and may demonstrate those bugs with small simple test programs written in *the C programming language*, do you not?

And, once you admit to that, the same applies to Python, Java, C++, C#, Visual Basic, JavaScript, PHP, assembly language - and so on down the Tiobe index - Objective-C, Objective-C++, Go, Rust, Swift, Fortran, Perl, Ruby, and so on?)

[decsep.c.txt](https://github.com/the-tcpdump-group/tcpdump/files/6948851/decsep.c.txt)

**Comment by guyharris** [comment]
> I built it with MSVC/Microsoft's-front-end-and-code-generator on Windows 10, set the region to France and the regional format to "France (French)", and ran the tests (msbuild check.vcxproj in the build directory), and the `802.11_exthdr` test passed.

...and tcpdump used a period as the decimal-point character, but `decsep ""` used a comma.

**Comment by gvanem** [comment]
> and the behavior of fprintf() with respect to the decimal-point character is controlled by the run-time library

I think all this is controlled by the global OS settings. At least when `setlocale()` is not called explicit.

Changing the decimal separator to `.` in this dialogue:
![value-formats](https://user-images.githubusercontent.com/945271/128596458-307643dc-e169-4947-8bbe-2bc75ed09ce8.png)

I get the *correct* `1.0 Mb/s` etc. I can even change it to print `1'0 Mb/s`.

**Comment by gvanem** [comment]
> ...and tcpdump used a period as the decimal-point character, but decsep "" used a comma.

Same as I get with both cl, clang-cl and gcc (TDM-gcc). They all use either `api-ms-win-crt-locale-l1-1-0.dll` or `msvcrt.dll`
where `setlocale()` is implemented. But underneath it goes into the Registry and uses the OS-global settings.

**Comment by guyharris** [comment]
So are your default settings

Region: Norwegian Bokmâl (Norway) or Norwegian Nynorsk (Norway)

System locale: the same

Windows display language: the same

**Comment by guyharris** [comment]
And, with your default settings, and no customization, what do:

- `decsep`;
- `decsep "C"`;
- `decsep ""`;

print?

**Comment by guyharris** [comment]
BTW, changing "Current language for non-Unicode programs" doesn't appear to make any difference.  I'm guessing from "language" that it's one of the settings that would affect things such as `LC_MESSAGES` but not `LC_NUMERIC`.

**Comment by guyharris** [comment]
What I'm trying to do is to determine, in your default environment whether:

1. Visual Studio conforms to C90/C99, and the "C" locale is similar to how it is on UN\*Xes, in which case both `decsep` and `decsep "C"` should always print "5.5";
2. Visual Studio conforms to C90/C99, and the "C" locale is *not* similar to how it is on UN\*Xes, in which case both `decsep` and `decsep "C"` might print "5,5", with the "C" locale using your default environment's decimal-point character;
3. Visual Studio *doesn't* conform to C90/C99, so that a program doesn't start out by default in the "C" locale, but the "C" locale is similar to how it is on UN\*Xes, in which case `decsep` would probably print "5,5" (i.e., programs default to a locale that reflects your default environment) but `decsep "C"` would print "5.5".

In all of those 3 cases, I'd expect `decsep ""` to print "5,5" in your default environment.

If the case is case 1, then I'd expect tcpdump to behave the same way; given that it's not behaving that way, something else is happening - perhaps some library it's calling is calling `setlocale({LC_ALL,LC_NUMERIC}, "")` (libpcap/WinPcap/Npcap don't call it at all).

If the case is case 2, that would explain tcpdump's behavior.  If we want to use "." as the decimal-point character, we'd have to pick some locale where the decimal-point character is "." and set `LC_NUMERIC` to that.

If the case is case 3, we could have tcpdump work around the bug by calling `setlocale(LC_ALL, "C")` itself.

The localization of formatted input and output is a bit annoying in that it doesn't make a difference between communicating with humans and communicating with other *programs* using text representations of non-integral numbers.

The current version of POSIX has some APIs that support per-thread locales and make it easier to do setting an unsetting; it would be nice if Windows 1) supported those APIs and 2) if they're not doing that already, support *some* locale in which the decimal-point character is guaranteed to be "." (the "C" locale would be nice, but if it doesn't make that guarantee on Windows, changing it to do so might cause compatibility issues).  If they provide something equivalent, we might be able to wrap that and the `newlocale()`/`uselocale()`/etc. APIs of POSIX.

**Comment by gvanem** [comment]
> And, with your default settings, and no customization, what do:

| Test  |  Output |
| :----------- | :-------------- |
| decsep  | `5.5` |
| decsep "C"  | `5.5` |
| decsep ""  | `5,5` |

(w/o the trailing `;` in `decsep;` that is).

**Comment by gvanem** [comment]
>  it would be nice if Windows 1) supported those APIs 

There is a `_configthreadlocale (_ENABLE_PER_THREAD_LOCALE)`. Ref: https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/configthreadlocale?view=msvc-160

I've not tried it.

**Comment by gvanem** [comment]
> In all of those 3 cases, I'd expect decsep "" to print "5,5" in your default environment.

It does. 

> If the case is case 1, then I'd expect tcpdump to behave the same way; given that it's not behaving that way, something 
> else is happening - perhaps some library it's calling is calling setlocale({LC_ALL,LC_NUMERIC}, "") 

Now after rebuilding `tcpdump` with the bare minimum of libraries (no OpenSSL, libsmi etc), I see that it prints `5.5` as it should.
Hard to tell what happened. But I'm just closing this issue.
