### ISSUE TITLE
Remove missing/win_ether_ntohost.c ?

### ISSUE THREAD

**Issue by fxlb** [the-tcpdump-group/tcpdump#971]
It was only used in some files of win32/ repository, removed.

Any reason to keep it?

**Comment by guyharris** [comment]
No - on systems that lack `ether_ntohost()`, such as Windows, `etheraddr_string()` generates the MAC address string itself.

This also means we clean up other stuff in addrtoname.c that handled the old case where we used missing/win_ether_ntohost.c.

**Comment by guyharris** [comment]
And Windows 7 and 10 appear not to have an ethers file; if the user wants name resolution for MAC addresses, they'd have to add their own ethers file and, unlike UN\*Xes, where there's some tradition of an /etc/ethers file, people are probably less likely to think "OK, I'll add some entries to the ethers file".  I guess win_ether_ntohost.c looks for ethers there because that's where the hosts file is.

**Comment by guyharris** [comment]
Done in d584b1caba87f30e88e20941d6ac6e87c3e8751a.

**Comment by fxlb** [comment]
Thanks!
